[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = -DARDUINO_USB_CDC_ON_BOOT=1
extra_scripts = pre:scripts/generate_content.py
lib_ldf_mode = deep+
lib_deps =
  adafruit/Adafruit NeoPixel@^1.12.0
  bblanchon/ArduinoJson@^7.0.4

; Este projeto usa atualmente a variante sem PSRAM.
; Se o seu modulo for uma variante com PSRAM (ex.: N8R8), descomente:
; board_build.arduino.memory_type = qio_opi
; build_flags = -DBOARD_HAS_PSRAM
